import { Procurement } from '../models/Procurement.js';
import { Booking } from '../models/Booking.js';
import { Settlement } from '../models/Settlement.js';
import { forbidden, notFound, badRequest } from '../utils/errors.js';

async function getBooking(id, actor) { const booking = await Booking.findById(id); if (!booking) throw notFound('Booking not found'); if (actor.role === 'farmer' && booking.farmerId.toString() !== actor._id.toString()) throw forbidden(); if (actor.role === 'staff' && !actor.assignedCentreIds.some((centreId) => centreId.toString() === booking.centreId.toString())) throw forbidden(); return booking; }
export async function getByBooking(id, actor) { await getBooking(id, actor); return Procurement.findOne({ bookingId: id }); }
export async function verify(id, input, actor) { const booking = await getBooking(id, actor); const record = await Procurement.findOneAndUpdate({ bookingId: id }, { bookingId: id, farmerId: booking.farmerId, centreId: booking.centreId, commodityId: booking.commodityId, commodityName: booking.commodityName, verificationStatus: input.verified ? 'verified' : 'failed', verifiedBy: actor._id, verifiedAt: new Date(), status: 'quality_check' }, { upsert: true, new: true, setDefaultsOnInsert: true }); booking.status = input.verified ? 'quality_check' : 'rejected'; await booking.save(); return record; }

export async function quality(id, input, actor) { const booking = await getBooking(id, actor); if (!input.qualityStatus) throw badRequest('qualityStatus is required'); const record = await Procurement.findOneAndUpdate({ bookingId: id }, { qualityStatus: input.qualityStatus, qualityGrade: input.qualityGrade, qualityRemarks: input.qualityRemarks, rejectionReason: input.rejectionReason, qualityCheckedBy: actor._id, qualityCheckedAt: new Date(), status: input.qualityStatus === 'rejected' ? 'rejected' : 'weighed' }, { new: true }); if (!record) throw notFound('Procurement record not found'); booking.status = input.qualityStatus === 'rejected' ? 'rejected' : 'weighed'; await booking.save(); return record; }
export async function weighing(id, input, actor) { const booking = await getBooking(id, actor); if (input.acceptedQuantity + input.rejectedQuantity !== input.actualWeighedQuantity) throw badRequest('Accepted and rejected quantities must equal actual weighed quantity'); const record = await Procurement.findOneAndUpdate({ bookingId: id }, { actualWeighedQuantity: input.actualWeighedQuantity, acceptedQuantity: input.acceptedQuantity, rejectedQuantity: input.rejectedQuantity, quantityUnit: input.quantityUnit || 'kg', weighedBy: actor._id, weighedAt: new Date(), status: input.acceptedQuantity === 0 ? 'rejected' : input.rejectedQuantity > 0 ? 'partially_accepted' : 'accepted' }, { new: true }); if (!record) throw notFound('Procurement record not found'); booking.status = record.status; await booking.save(); return record; }
export async function complete(id, actor) { const booking = await getBooking(id, actor); const record = await Procurement.findOneAndUpdate({ bookingId: id, status: { $in: ['accepted', 'partially_accepted'] } }, { status: 'completed', completedBy: actor._id, completedAt: new Date() }, { new: true }); if (!record) throw badRequest('Procurement must be accepted before completion'); booking.status = 'completed'; await booking.save(); return record; }
export async function createSettlement(input, actor) { const booking = await getBooking(input.bookingId, actor); return Settlement.findOneAndUpdate({ bookingId: booking._id }, { ...input, farmerId: booking.farmerId, centreId: booking.centreId, createdBy: actor._id, updatedBy: actor._id }, { upsert: true, new: true, setDefaultsOnInsert: true }); }
export const getSettlement = (id, actor) => getBooking(id, actor).then(() => Settlement.findOne({ bookingId: id }));
