import * as centres from '../services/centreService.js';
import * as commodities from '../services/commodityService.js';
import * as slots from '../services/slotService.js';
import * as bookings from '../services/booking/bookingService.js';
import * as queue from '../services/queue/queueService.js';
import { success } from '../utils/response.js';
import { emitQueueUpdate } from '../sockets/index.js';

export const listCentres = async (req, res) => success(res, await centres.list(req.query));
export const getCentre = async (req, res) => success(res, await centres.get(req.params.id));
export const createCentre = async (req, res) => success(res, await centres.create(req.body, req.user), 201);
export const updateCentre = async (req, res) => success(res, await centres.update(req.params.id, req.body, req.user));
export const setCentreStatus = async (req, res) => success(res, await centres.setStatus(req.params.id, req.body.status, req.user));
export const listCommodities = async (req, res) => success(res, req.user?.role === 'admin' ? await commodities.listAll() : await commodities.list());
export const createCommodity = async (req, res) => success(res, await commodities.create(req.body, req.user), 201);
export const updateCommodity = async (req, res) => success(res, await commodities.update(req.params.id, req.body, req.user));
export const listSlots = async (req, res) => success(res, await slots.list(req.query));
export const getSlot = async (req, res) => success(res, await slots.get(req.params.id));
export const createSlot = async (req, res) => success(res, await slots.create(req.body, req.user), 201);
export const updateSlot = async (req, res) => success(res, await slots.update(req.params.id, req.body, req.user));
export const setSlotStatus = async (req, res) => success(res, await slots.update(req.params.id, { active: req.body.active }, req.user));
export const createBooking = async (req, res) => success(res, await bookings.create(req.body, req.user), 201);
export const myBookings = async (req, res) => success(res, await bookings.mine(req.user._id));
export const getBooking = async (req, res) => success(res, await bookings.get(req.params.id, req.user));
export const getBookingQueue = async (req, res) => success(res, await queue.forBooking(req.params.id, req.user));
export const cancelBooking = async (req, res) => success(res, await bookings.cancel(req.params.id, req.user, req.body.reason));
export const checkIn = async (req, res) => success(res, await queue.checkIn(req.params.bookingId, req.user));
export const listQueue = async (req, res) => success(res, await queue.list(req.query, req.user));
export const updateQueue = async (req, res) => { const result = await queue.updateStatus(req.params.id, req.body.status, req.user); emitQueueUpdate(result); return success(res, result); };
export const skipQueue = async (req, res) => success(res, await queue.skip(req.params.id, req.user, req.body.reason));
