import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import { authorize } from '../middleware/authorize.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import * as controller from '../controllers/resourceController.js';
import * as scheduleController from '../controllers/scheduleController.js';
import { bookingSchema, cancelSchema, centreSchema, commoditySchema, queueStatusSchema, skipSchema, slotSchema, procurementScheduleSchema, schedulePreviewSchema } from '../validators/resources.js';

const router = Router();
const protectedPath = /^\/(bookings|staff|admin)(\/|$)/;
router.get('/centres', asyncHandler(controller.listCentres));
router.get('/centres/:id', asyncHandler(controller.getCentre));
router.get('/commodities', asyncHandler(controller.listCommodities));
router.get('/slots', asyncHandler(controller.listSlots));
router.get('/slots/:id', asyncHandler(controller.getSlot));
router.use((request, response, next) => protectedPath.test(request.path) ? authenticate(request, response, next) : next());
router.post('/bookings', authorize('farmer'), validate(bookingSchema), asyncHandler(controller.createBooking));
router.get('/bookings/my', authorize('farmer'), asyncHandler(controller.myBookings));
router.get('/bookings/:id/queue', asyncHandler(controller.getBookingQueue));
router.get('/bookings/:id', asyncHandler(controller.getBooking));
router.post('/bookings/:id/cancel', authorize('farmer', 'staff', 'admin'), validate(cancelSchema), asyncHandler(controller.cancelBooking));
router.get('/staff/queue', authorize('staff', 'admin'), asyncHandler(controller.listQueue));
router.post('/staff/bookings/:bookingId/check-in', authorize('staff', 'admin'), asyncHandler(controller.checkIn));
router.patch('/staff/queue/:id/status', authorize('staff', 'admin'), validate(queueStatusSchema), asyncHandler(controller.updateQueue));
router.post('/staff/queue/:id/skip', authorize('staff', 'admin'), validate(skipSchema), asyncHandler(controller.skipQueue));
router.post('/admin/centres', authorize('admin'), validate(centreSchema), asyncHandler(controller.createCentre));
router.patch('/admin/centres/:id', authorize('admin'), validate(centreSchema.partial()), asyncHandler(controller.updateCentre));
router.patch('/admin/centres/:id/status', authorize('admin'), asyncHandler(controller.setCentreStatus));
router.get('/admin/slots', authorize('admin'), asyncHandler(controller.listAdminSlots));
router.post('/admin/commodities', authorize('admin'), validate(commoditySchema), asyncHandler(controller.createCommodity));
router.patch('/admin/commodities/:id', authorize('admin'), validate(commoditySchema.partial()), asyncHandler(controller.updateCommodity));
router.post('/admin/slots', authorize('admin'), validate(slotSchema), asyncHandler(controller.createSlot));
router.patch('/admin/slots/:id', authorize('admin'), validate(slotSchema.partial()), asyncHandler(controller.updateSlot));
router.patch('/admin/slots/:id/status', authorize('admin'), asyncHandler(controller.setSlotStatus));
router.post('/admin/schedules/preview', authorize('admin'), validate(schedulePreviewSchema), asyncHandler(scheduleController.previewSchedule));
router.post('/admin/schedules', authorize('admin'), validate(procurementScheduleSchema), asyncHandler(scheduleController.createSchedule));
router.get('/admin/schedules', authorize('admin'), asyncHandler(scheduleController.listSchedules));
router.get('/admin/schedules/:id', authorize('admin'), asyncHandler(scheduleController.getSchedule));
router.get('/admin/schedules/:id/slots', authorize('admin'), asyncHandler(scheduleController.getScheduleSlots));
router.patch('/admin/schedules/:id/status', authorize('admin'), asyncHandler(scheduleController.setScheduleStatus));
export default router;

