import { BarChart3, Building2, CheckCircle2, Clock3, Gauge, MapPin, Settings2, UsersRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button, LoadingSpinner, Modal, StatCard, StatusBadge } from '../components/UI';
import { api } from '../services/api';
import { useApp } from '../context/AppContext';

const errorText = (error) => error.response?.data?.message || 'Unable to load admin data.';

export function AdminDashboard() { const [data, setData] = useState(null); const { notify } = useApp(); useEffect(() => { api.getAdminDashboard().then(setData).catch((error) => notify(errorText(error), 'error')); }, []); if (!data) return <div className="dashboard-page"><LoadingSpinner /></div>; return <div className="dashboard-page admin-page"><div className="welcome-row"><div><span className="eyebrow">PROCUREMENT OVERVIEW</span><h2>District procurement overview</h2><p>Metrics are calculated from the current database.</p></div><Button to="/admin/centres">Manage centres</Button></div><section className="admin-stats"><StatCard icon={Building2} value={data.totalCentres} label="Active centres" note="Current database" accent="blue" /><StatCard icon={UsersRound} value={data.totalFarmers} label="Active farmers" note="Registered accounts" accent="green" /><StatCard icon={Gauge} value={data.activeBookings} label="Active bookings" note="Capacity-consuming records" accent="gold" /><StatCard icon={BarChart3} value="—" label="Procurement value" note="Settlement analytics pending" accent="blue" /><StatCard icon={Clock3} value="—" label="Average waiting" note="Calculated from queue history" accent="green" /></section><section className="analytics-note"><BarChart3 /><div><b>Analytics data is operational</b><p>Detailed charts will appear as procurement and queue history accumulates.</p></div></section></div>; }

export function AdminCentresPage() { const [items, setItems] = useState([]); const [editing, setEditing] = useState(null); const { notify } = useApp(); const load = () => api.getCentres({ status: 'active' }).then((result) => setItems(result.items || result)).catch((error) => notify(errorText(error), 'error')); useEffect(() => { load(); }, []); const save = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const payload = { centreCode: data.centreCode, name: data.name, address: data.address, district: data.district, state: data.state, status: 'active' }; if (editing?._id) await api.updateCentre(editing._id, payload); else await api.createCentre(payload); setEditing(null); await load(); notify('Centre saved.'); } catch (error) { notify(errorText(error), 'error'); } }; return <div className="dashboard-page admin-page"><div className="page-intro split"><div><span className="eyebrow">CENTRE MANAGEMENT</span><h2>Manage procurement centres</h2><p>Only administrators can change centre configuration.</p></div><Button onClick={() => setEditing({})}>Add centre</Button></div><section className="admin-table-card"><table className="admin-table"><thead><tr><th>Centre</th><th>District</th><th>Address</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><b>{item.name}</b><small>{item.centreCode}</small></td><td>{item.district}</td><td>{item.address}</td><td><StatusBadge status={item.status} /></td><td><button className="text-button" onClick={() => setEditing(item)}>Edit</button></td></tr>)}</tbody></table></section>{editing && <Modal title={editing._id ? 'Edit procurement centre' : 'Add procurement centre'} onClose={() => setEditing(null)}><form className="modal-form" onSubmit={save}><label>Centre code<input name="centreCode" defaultValue={editing.centreCode || ''} required /></label><label>Centre name<input name="name" defaultValue={editing.name || ''} required /></label><label className="full">Address<input name="address" defaultValue={editing.address || ''} required /></label><label>District<input name="district" defaultValue={editing.district || ''} required /></label><label>State<input name="state" defaultValue={editing.state || ''} required /></label><div className="modal-actions full"><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button type="submit">Save centre</Button></div></form></Modal>}</div>; }

export function AdminAnalyticsPage() { return <div className="dashboard-page admin-page"><div className="page-intro"><span className="eyebrow">ANALYTICS</span><h2>Operational signals across centres</h2><p>Analytics will be calculated from real bookings, queue and procurement records.</p></div><section className="analytics-note"><BarChart3 /><div><b>No historical data yet</b><p>Charts will populate as the empty production database receives operational records.</p></div></section></div>; }

export function AdminStaffPage() {
	const [staff, setStaff] = useState([]); const [centres, setCentres] = useState([]); const [editing, setEditing] = useState(null); const [centreIds, setCentreIds] = useState([]); const { notify } = useApp();
	const load = async () => { try { const [staffData, centreData] = await Promise.all([api.getStaffUsers(), api.getCentres({ status: 'active' })]); setStaff(staffData); setCentres(centreData.items || centreData); } catch (error) { notify(errorText(error), 'error'); } };
	useEffect(() => { load(); }, []);
	const openCreate = () => { setEditing({}); setCentreIds([]); };
	const openEdit = (item) => { setEditing(item); setCentreIds((item.assignedCentreIds || []).map((centre) => centre._id || centre)); };
	const save = async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const payload = { name: data.name, email: data.email, mobile: data.mobile, preferredLanguage: data.preferredLanguage, assignedCentreIds: centreIds }; if (!editing?._id) payload.password = data.password; try { if (editing?._id) await api.updateStaff(editing._id, payload); else await api.createStaff(payload); setEditing(null); await load(); notify(editing?._id ? 'Staff account updated.' : 'Staff account created.'); } catch (error) { notify(errorText(error), 'error'); } };
	const toggleStatus = async (item) => { const status = item.status === 'active' ? 'suspended' : 'active'; try { await api.updateStaff(item._id, { status }); await load(); notify(status === 'active' ? 'Staff account activated.' : 'Staff account suspended.'); } catch (error) { notify(errorText(error), 'error'); } };
	return <div className="dashboard-page admin-page"><div className="page-intro split"><div><span className="eyebrow">STAFF MANAGEMENT</span><h2>Manage centre staff</h2><p>Create staff accounts and control their assigned procurement centres.</p></div><Button onClick={openCreate}>Create Staff</Button></div><section className="admin-table-card"><table className="admin-table"><thead><tr><th>Name</th><th>Contact</th><th>Assigned centres</th><th>Status</th><th>Actions</th></tr></thead><tbody>{staff.map((item) => <tr key={item._id}><td><b>{item.name}</b><small>{item.role}</small></td><td><small>{item.email}</small><small>{item.mobile}</small></td><td>{item.assignedCentreIds?.length ? item.assignedCentreIds.map((centre) => centre.name || centre).join(', ') : 'No centres assigned'}</td><td><StatusBadge status={item.status} /></td><td><button className="text-button" onClick={() => openEdit(item)}>Edit</button> <button className="text-button" onClick={() => toggleStatus(item)}>{item.status === 'active' ? 'Deactivate' : 'Reactivate'}</button></td></tr>)}</tbody></table>{!staff.length && <div className="empty-state"><UsersRound size={30} /><h3>No staff accounts</h3><p>Create the first staff account for your procurement centres.</p></div>}</section>{editing && <Modal title={editing._id ? 'Edit staff account' : 'Create staff account'} onClose={() => setEditing(null)}><form className="modal-form" onSubmit={save}><label>Staff name<input name="name" defaultValue={editing.name || ''} required /></label><label>Email<input name="email" type="email" defaultValue={editing.email || ''} required /></label><label>Mobile number<input name="mobile" inputMode="numeric" maxLength="10" defaultValue={editing.mobile || ''} required /></label>{!editing._id && <label>Password<input name="password" type="password" minLength="8" required /></label>}<label>Preferred language<select name="preferredLanguage" defaultValue={editing.preferredLanguage || 'en'}><option value="en">English</option><option value="hi">Hindi</option></select></label><label className="full">Assigned procurement centres<select className="multi-select" multiple value={centreIds} onChange={(event) => setCentreIds(Array.from(event.target.selectedOptions, (option) => option.value))}>{centres.map((centre) => <option key={centre._id} value={centre._id}>{centre.name} · {centre.district}</option>)}</select></label><div className="modal-actions full"><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button type="submit">{editing._id ? 'Save changes' : 'Create Staff'}</Button></div></form></Modal>}</div>;
}

export function AdminPlaceholderPage({ type }) { const details = { schedules: ['Slot management', 'Create and configure individual centre slots through the backend.'], settings: ['System settings', 'System-level configuration is managed through environment variables initially.'] }; const [title, text] = details[type] || details.settings; return <div className="dashboard-page admin-page"><div className="placeholder-page"><span className="icon-box blue"><Settings2 size={27} /></span><span className="eyebrow">ADMIN MODULE</span><h2>{title}</h2><p>{text}</p><Button to="/admin/dashboard">Return to dashboard</Button></div></div>; }
