import { BarChart3, Building2, CalendarClock, CheckCircle2, Clock3, Gauge, MapPin, Settings2, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Button, Modal, StatCard, StatusBadge } from '../components/UI';
import { centres } from '../data/centres';
import { arrivals } from '../data/dashboard';
import { useApp } from '../context/AppContext';

function ChartCard({ title, detail, children }) { return <article className="chart-card"><div><h3>{title}</h3><p>{detail}</p></div><div className="chart-wrap">{children}</div></article>; }

export function AdminDashboard() { return <div className="dashboard-page admin-page"><div className="welcome-row"><div><span className="eyebrow">DISTRICT PROCUREMENT OVERVIEW</span><h2>Good morning, District Admin.</h2><p>Operational visibility across the Meerut demo network.</p></div><Button to="/admin/centres">Manage centres</Button></div><section className="admin-stats"><StatCard icon={Building2} value="28" label="Total centres" note="Across demo district" accent="blue" /><StatCard icon={UsersRound} value="4,820" label="Farmers today" note="Illustrative volume" accent="green" /><StatCard icon={Gauge} value="19" label="Active queues" note="Centres receiving farmers" accent="gold" /><StatCard icon={BarChart3} value="₹82.4L" label="Procurement today" note="Illustrative value" accent="blue" /><StatCard icon={Clock3} value="31 min" label="Average waiting" note="Target below 35 minutes" accent="green" /></section><section className="centre-health"><div className="section-row"><div><span className="eyebrow">CENTRE PERFORMANCE</span><h2>Watch congestion before it grows.</h2></div><Button to="/admin/analytics" variant="secondary">View analytics</Button></div><div className="health-list">{centres.slice(0, 3).map((centre, index) => <div key={centre.id}><span className={`health-icon ${index === 2 ? 'high' : index === 1 ? 'moderate' : ''}`}><MapPin size={19} /></span><div><b>{index === 0 ? 'Centre A' : index === 1 ? 'Centre B' : 'Centre C'}</b><p>{centre.name} • {centre.queue} farmers in queue</p></div><StatusBadge status={centre.status === 'Normal' ? 'Normal' : centre.status === 'Moderate' ? 'Moderate' : 'High Congestion'} /><span className="mini-capacity"><i style={{ width: `${centre.capacity}%` }}></i>{centre.capacity}%</span></div>)}</div></section><section className="chart-grid"><ChartCard title="Daily farmer arrivals" detail="Illustrative six-day trend"><ResponsiveContainer width="100%" height="100%"><LineChart data={arrivals}><CartesianGrid vertical={false} stroke="#e8eee9" /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey="farmers" stroke="#0f5b37" strokeWidth={3} dot={{ r: 4 }} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Centre capacity utilisation" detail="Average allocation by day"><ResponsiveContainer width="100%" height="100%"><BarChart data={arrivals}><CartesianGrid vertical={false} stroke="#e8eee9" /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="procurement" fill="#d99a18" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></section></div>; }

export function AdminCentresPage() { const [items, setItems] = useState(centres); const [editing, setEditing] = useState(null); const { notify } = useApp(); const save = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); if (editing?.id) setItems((list) => list.map((item) => item.id === editing.id ? { ...item, ...data, capacity: Number(data.capacity) } : item)); else setItems((list) => [...list, { id: `new-${list.length}`, name: data.name, location: data.location, district: data.district, capacity: Number(data.capacity), queue: 0, distance: '—', slots: 12, status: 'Normal' }]); setEditing(null); notify('Centre details updated in this demo.'); };
  return <div className="dashboard-page admin-page"><div className="page-intro split"><div><span className="eyebrow">CENTRE MANAGEMENT</span><h2>Manage procurement centre readiness</h2><p>Add centres, set capacity and update working hours. Changes are demo-only.</p></div><Button onClick={() => setEditing({})}>Add centre</Button></div><section className="admin-table-card"><table className="admin-table"><thead><tr><th>Centre</th><th>District</th><th>Capacity</th><th>Working hours</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><b>{item.name}</b><small>{item.location}</small></td><td>{item.district}</td><td><span className="capacity-cell"><i style={{ width: `${item.capacity}%` }}></i>{item.capacity}%</span></td><td>9:00 AM – 5:00 PM</td><td><StatusBadge status={item.status} /></td><td><button className="text-button" onClick={() => setEditing(item)}>Edit</button></td></tr>)}</tbody></table></section>{editing && <Modal title={editing.id ? 'Edit procurement centre' : 'Add procurement centre'} onClose={() => setEditing(null)}><form className="modal-form" onSubmit={save}><label>Centre name<input name="name" defaultValue={editing.name || ''} required /></label><label>Location<input name="location" defaultValue={editing.location || ''} required /></label><label>District<select name="district" defaultValue={editing.district || 'Meerut'}><option>Meerut</option><option>Hapur</option><option>Ghaziabad</option></select></label><label>Daily capacity (%)<input name="capacity" type="number" min="1" max="100" defaultValue={editing.capacity || 70} required /></label><label className="full">Working hours<select name="hours" defaultValue="9:00 AM – 5:00 PM"><option>9:00 AM – 5:00 PM</option><option>8:00 AM – 4:00 PM</option><option>10:00 AM – 6:00 PM</option></select></label><div className="modal-actions full"><Button type="button" variant="secondary" onClick={() => setEditing(null)}>Cancel</Button><Button type="submit">Save centre</Button></div></form></Modal>}</div>; }

export function AdminAnalyticsPage() { return <div className="dashboard-page admin-page"><div className="page-intro"><span className="eyebrow">ANALYTICS</span><h2>Operational signals across centres</h2><p>All charts use illustrative SIH prototype data, not official procurement statistics.</p></div><section className="chart-grid analytics-charts"><ChartCard title="Average waiting time" detail="Minutes by operational day"><ResponsiveContainer width="100%" height="100%"><LineChart data={arrivals}><CartesianGrid vertical={false} stroke="#e8eee9" /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip /><Line type="monotone" dataKey="wait" stroke="#2160b8" strokeWidth={3} /></LineChart></ResponsiveContainer></ChartCard><ChartCard title="Procurement volume" detail="Illustrative quintals accepted"><ResponsiveContainer width="100%" height="100%"><BarChart data={arrivals}><CartesianGrid vertical={false} stroke="#e8eee9" /><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Legend /><Tooltip /><Bar dataKey="procurement" name="Quintals" fill="#0f5b37" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard></section><section className="analytics-note"><BarChart3 /><div><b>Prototype prediction signal</b><p>Centre B is likely to see moderate congestion on Friday between 11:00 AM and 12:00 PM. A future backend can source this from queue and capacity telemetry.</p></div></section></div>; }

export function AdminPlaceholderPage({ type }) { const details = { schedules: ['Schedule management', 'Create centre windows and commodity allocations.'], staff: ['Staff management', 'View assigned staff and operational permissions.'], settings: ['System settings', 'Configure language, notification and integration preferences.'] }; const [title, text] = details[type] || details.settings; return <div className="dashboard-page admin-page"><div className="placeholder-page"><span className="icon-box blue"><Settings2 size={27} /></span><span className="eyebrow">ADMIN MODULE</span><h2>{title}</h2><p>{text} This prototype view is deliberately kept light while the core farmer, queue, staff and analytics flows are fully demonstrated.</p><Button to="/admin/dashboard">Return to dashboard</Button></div></div>; }
