import { ArrowLeft, CheckCircle2, LockKeyhole, Phone, ShieldCheck, UserRound } from 'lucide-react';
import { useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Button, Logo } from '../components/UI';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';

const rolePath = { farmer: '/farmer/dashboard', staff: '/staff/dashboard', admin: '/admin/dashboard' };

export function LoginPage() {
  const [params] = useSearchParams(); const navigate = useNavigate(); const { notify } = useApp();
  const [role, setRole] = useState(params.get('role') || 'farmer'); const [mobile, setMobile] = useState(''); const [otp, setOtp] = useState(''); const [step, setStep] = useState('mobile'); const [loading, setLoading] = useState(false);
  const sendOtp = (event) => { event.preventDefault(); if (mobile.replace(/\D/g, '').length !== 10) return notify('Enter a valid 10-digit mobile number.', 'error'); setStep('otp'); notify('Demo OTP sent. Use 123456 to continue.'); };
  const login = async (event) => { event.preventDefault(); if (otp !== '123456') return notify('Use prototype OTP: 123456', 'error'); setLoading(true); await api.loginUser({ mobile, role }); notify('Signed in to the demo portal.'); navigate(rolePath[role]); };
  return <main className="auth-page"><div className="auth-top"><Logo /><Link to="/"><ArrowLeft size={16} /> Back to website</Link></div><div className="auth-layout"><section className="auth-intro"><span className="eyebrow">SECURE PROTOTYPE ACCESS</span><h1>Welcome to<br />Krishi Nova.</h1><p>One connected service for a clearer, more farmer-friendly procurement journey.</p><div className="auth-points"><span><ShieldCheck /> Transparent information at every stage</span><span><CheckCircle2 /> Smart slot recommendations</span><span><LockKeyhole /> OTP-based demo access</span></div></section><section className="auth-card"><div className="auth-card-heading"><span className="icon-box green"><Phone /></span><div><h2>Sign in</h2><p>Use your mobile number to continue.</p></div></div><div className="role-switch" aria-label="Select portal role">{['farmer', 'staff', 'admin'].map((item) => <button className={role === item ? 'active' : ''} onClick={() => setRole(item)} key={item}>{item}</button>)}</div>{step === 'mobile' ? <form onSubmit={sendOtp}><label>Mobile number<input value={mobile} onChange={(event) => setMobile(event.target.value)} inputMode="numeric" maxLength="10" placeholder="Enter 10-digit mobile number" autoFocus required /></label><p className="input-help">We will send a one-time password to this number.</p><Button type="submit" className="wide">Send OTP</Button></form> : <form onSubmit={login}><button type="button" className="back-link" onClick={() => setStep('mobile')}><ArrowLeft size={16} /> Change mobile number</button><label>Enter one-time password<input value={otp} onChange={(event) => setOtp(event.target.value)} inputMode="numeric" maxLength="6" placeholder="••••••" autoFocus required /></label><p className="otp-note"><b>Prototype OTP: 123456</b><br />No real OTP is sent in this demo.</p><Button type="submit" className="wide" disabled={loading}>{loading ? 'Signing in…' : `Continue as ${role}`}</Button></form>}<p className="auth-footer">New farmer? <Link to="/register">Create your account</Link></p></section></div></main>;
}

export function RegisterPage() {
  const navigate = useNavigate(); const { notify } = useApp(); const [loading, setLoading] = useState(false);
  const register = async (event) => { event.preventDefault(); setLoading(true); const data = Object.fromEntries(new FormData(event.currentTarget)); await api.registerFarmer(data); notify('Registration saved for this prototype.'); navigate('/farmer/dashboard'); };
  return <main className="auth-page register-page"><div className="auth-top"><Logo /><Link to="/login"><ArrowLeft size={16} /> Back to sign in</Link></div><section className="register-card"><div className="auth-card-heading"><span className="icon-box green"><UserRound /></span><div><h1>Create your farmer account</h1><p>Keep your procurement details ready with a simple profile.</p></div></div><form className="form-grid" onSubmit={register}><label className="full">Full name<input name="name" placeholder="e.g. Ramesh Kumar" required /></label><label>Mobile number<input name="mobile" inputMode="numeric" maxLength="10" placeholder="10-digit number" required /></label><label>Farmer ID<input name="farmerId" placeholder="e.g. KNF-8421" required /></label><label>State<select name="state" defaultValue=""><option value="" disabled>Select state</option><option>Uttar Pradesh</option><option>Punjab</option><option>Haryana</option></select></label><label>District<select name="district" defaultValue=""><option value="" disabled>Select district</option><option>Meerut</option><option>Hapur</option><option>Ghaziabad</option></select></label><label>Village<input name="village" placeholder="Your village name" required /></label><label>Preferred language<select name="language" defaultValue="English"><option>English</option><option>हिंदी</option></select></label><div className="full form-consent"><ShieldCheck size={18} /> This prototype collects no real identity information. Do not enter Aadhaar or banking details.</div><Button type="submit" className="wide" disabled={loading}>{loading ? 'Creating account…' : 'Create account'}</Button></form></section></main>;
}
