import { Bell, CalendarCheck2, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileCheck2, MapPin, ReceiptText, Radio, Sprout, Truck, UsersRound, Wheat } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button, CentreCard, LoadingSpinner, SectionTitle, SlotCard, StatusBadge, Timeline } from '../components/UI';
import { centres } from '../data/centres';
import { slots } from '../data/slots';
import { queueTokens } from '../data/queue';
import { notifications } from '../data/notifications';
import { api } from '../services/api';
import { useApp } from '../context/AppContext';

const farmerActions = [
  [CalendarCheck2, 'Book new slot', 'Choose a time with an expected wait', '/farmer/book-slot'], [ReceiptText, 'My booking', 'Token and centre details', '/farmer/booking'],
  [UsersRound, 'Live queue', 'Position 8 • 27 min estimated', '/farmer/queue'], [FileCheck2, 'Procurement status', 'Weighing in progress', '/farmer/procurement'],
  [CircleDollarSign, 'Payment status', 'Payment initiated', '/farmer/payment'], [Bell, 'Notifications', '2 new messages', '/farmer/notifications'],
];

export function FarmerDashboard() { return <div className="dashboard-page farmer-dashboard"><div className="welcome-row"><div><span className="eyebrow">GOOD MORNING, RAMESH</span><h2>Your procurement day, made simpler.</h2><p>Here is the latest on your confirmed booking.</p></div><Button to="/farmer/book-slot">Book new slot</Button></div><section className="today-status"><div className="today-status-top"><div><span className="status status-confirmed"><i></i>Booking confirmed</span><h2>Today’s procurement status</h2><p>Government Procurement Centre • Meerut</p></div><span className="token-chip">TOKEN <b>P1024</b></span></div><div className="today-details"><div><MapPin /><span><small>Centre</small><b>Government Procurement Centre</b></span></div><div><Clock3 /><span><small>Expected waiting</small><b>27 min</b></span></div><div><UsersRound /><span><small>Queue position</small><b>8</b></span></div><Button to="/farmer/queue" variant="secondary">View live queue</Button></div></section><section><SectionTitle eyebrow="QUICK ACTIONS" title="Everything important, in one place" /><div className="farmer-action-grid">{farmerActions.map(([Icon, title, text, to]) => <Link to={to} className="farmer-action" key={title}><span><Icon size={22} /></span><div><b>{title}</b><p>{text}</p></div><ChevronRight size={19} /></Link>)}</div></section><section className="smart-prompt"><div><span className="prompt-icon"><Sprout /></span><div><span className="eyebrow">SMART SLOT INSIGHT</span><h3>Tomorrow’s lowest predicted wait is 20 minutes.</h3><p>12:00–1:00 PM has the clearest capacity at your nearby centre, based on demo queue conditions.</p></div></div><Button to="/farmer/book-slot" variant="secondary">See suggested slot</Button></section></div>; }

export function BookSlotPage() {
  const navigate = useNavigate(); const { notify, setBooking } = useApp(); const [commodity, setCommodity] = useState('Wheat'); const [centre, setCentre] = useState(centres[0]); const [slot, setSlot] = useState(slots.find((item) => item.recommended)); const [loading, setLoading] = useState(false);
  const book = async () => { setLoading(true); const response = await api.createBooking({ commodity, centre, time: slot.time, wait: slot.wait }); setBooking(response); notify('Your smart slot has been booked.'); navigate('/farmer/booking'); };
  return <div className="dashboard-page booking-page"><div className="page-intro"><span className="eyebrow">SMART SLOT BOOKING</span><h2>Plan your visit around a shorter queue.</h2><p>Choose a commodity and centre. Krishi Nova’s demo recommendation highlights the slot with the lowest predicted wait.</p></div><div className="booking-steps"><span className="active">1. Commodity</span><i></i><span className="active">2. Centre</span><i></i><span className="active">3. Smart slot</span></div><section className="booking-section"><div className="booking-section-title"><span>01</span><div><h3>Select commodity</h3><p>Choose what you are bringing to the centre.</p></div></div><div className="commodity-options">{['Wheat', 'Paddy', 'Maize'].map((item) => <button key={item} className={commodity === item ? 'selected' : ''} onClick={() => setCommodity(item)}><Wheat size={24} /><b>{item}</b><small>{item === 'Wheat' ? 'Rabi procurement' : 'Available at selected centres'}</small><i>{commodity === item && <Check size={15} />}</i></button>)}</div></section><section className="booking-section"><div className="booking-section-title"><span>02</span><div><h3>Select procurement centre</h3><p>Choose a nearby centre with suitable availability.</p></div></div><div className="booking-centres">{centres.slice(0, 3).map((item) => <button key={item.id} className={centre.id === item.id ? 'selected' : ''} onClick={() => setCentre(item)}><MapPin /><span><b>{item.name}</b><small>{item.location} • {item.distance}</small></span><StatusBadge status={item.status} /><i>{centre.id === item.id && <Check size={15} />}</i></button>)}</div></section><section className="booking-section"><div className="booking-section-title"><span>03</span><div><h3>Choose your slot</h3><p>Available on 10 September 2026 at {centre.name}.</p></div></div><div className="slot-grid">{slots.map((item) => <SlotCard key={item.id} slot={item} selected={slot.id === item.id} onSelect={setSlot} />)}</div></section><section className="recommend-book"><div><span className="demo-pill">★ ML Recommendation (Demo)</span><h3>{slot.recommended ? 'Recommended slot: ' : 'Selected slot: '}<b>{slot.time}</b></h3><p><b>Expected waiting: {slot.wait}</b> • {slot.label}</p></div><Button onClick={book} disabled={loading}>{loading ? 'Booking…' : slot.recommended ? 'Book recommended slot' : 'Book selected slot'}</Button></section></div>;
}

export function BookingPage() { const { booking } = useApp(); const info = booking || { id: 'KN-2026-1024', token: 'P1024', time: '12:00 – 1:00 PM', centre: centres[0], wait: '20 min', commodity: 'Wheat' }; return <div className="dashboard-page confirmation-page"><div className="confirmation-card"><span className="confirmation-icon"><Check size={40} /></span><span className="eyebrow">BOOKING CONFIRMED</span><h2>Slot Successfully Booked</h2><p>Your visit is now reserved. Please arrive at the centre around your booked time and carry your relevant procurement documents.</p><div className="booking-summary"><div><small>Booking ID</small><b>{info.id}</b></div><div><small>Centre</small><b>{info.centre?.name || centres[0].name}</b></div><div><small>Date</small><b>10 September 2026</b></div><div><small>Time</small><b>{info.time}</b></div><div><small>Expected waiting</small><b>{info.wait || '20 min'}</b></div></div><div className="token-qr"><div className="qr-pattern" aria-label="Demo QR token visual"></div><div><small>YOUR TOKEN</small><strong>{info.token}</strong><p>Show this token at centre check-in.</p></div></div><div className="confirmation-actions"><Button to="/farmer/queue">View live queue</Button><Button to="/farmer/dashboard" variant="secondary">Back to dashboard</Button></div></div></div>; }

export function QueuePage() { const [seconds, setSeconds] = useState(24); useEffect(() => { const interval = window.setInterval(() => setSeconds((value) => value === 0 ? 24 : value - 1), 1000); return () => window.clearInterval(interval); }, []); return <div className="dashboard-page queue-page"><div className="live-label"><Radio size={16} /> Live demo update <span>refreshes in {seconds}s</span></div><div className="queue-overview"><div className="queue-token"><small>YOUR TOKEN</small><strong>P1024</strong><StatusBadge status="Waiting" /></div><div className="queue-stat"><small>Current position</small><strong>8</strong><span>of 23 in active queue</span></div><div className="queue-stat"><small>Farmers ahead</small><strong>7</strong><span>Serving token P1017 now</span></div><div className="queue-stat highlight"><small>Estimated waiting</small><strong>27 <em>min</em></strong><span>Demo prediction</span></div></div><section className="queue-timeline-section"><div><span className="eyebrow">CENTRE QUEUE</span><h2>Follow your place in line</h2><p>The queue view is designed for future WebSocket/SSE live updates. It currently uses simulated demo data.</p></div><div className="token-list">{queueTokens.map((item) => <div className={item.state} key={item.token}><span>{item.state === 'served' ? <Check size={15} /> : item.state === 'you' ? <Radio size={15} /> : <Clock3 size={15} />}</span><b>{item.token}</b>{item.state === 'you' && <em>YOU</em>}<small>{item.state === 'served' ? 'Completed' : item.state === 'you' ? 'Waiting' : 'In queue'}</small></div>)}</div></section></div>; }

const procurementSteps = [
  { title: 'Slot Booked', description: 'Smart slot confirmed at Government Procurement Centre.', time: '09 Sep 2026, 4:12 PM', status: 'done' },
  { title: 'Farmer Arrived', description: 'Check-in completed at the centre desk.', time: '10 Sep 2026, 11:57 AM', status: 'done' },
  { title: 'Quality Check', description: 'Quality verification completed successfully.', time: '10 Sep 2026, 12:12 PM', status: 'done' },
  { title: 'Weighing', description: 'Your wheat is currently being weighed.', time: '10 Sep 2026, 12:18 PM', status: 'current' },
  { title: 'Procurement Completed', description: 'Procurement receipt will be issued.', status: 'future' },
  { title: 'Payment Initiated', description: 'Payment status will be updated here.', status: 'future' },
  { title: 'Payment Completed', description: 'Completion reference will appear here.', status: 'future' },
];
export function ProcurementPage() { return <div className="dashboard-page status-page"><div className="page-intro"><span className="eyebrow">PROCUREMENT STATUS</span><h2>Stay informed through every stage.</h2><p>Current booking: P1024 • Government Procurement Centre • 25 quintals wheat</p></div><section className="status-timeline-card"><div className="timeline-heading"><div><h3>Procurement progress</h3><p>Last updated: 10 Sep 2026, 12:18 PM</p></div><StatusBadge status="Weighing" /></div><Timeline items={procurementSteps} current="Weighing" /></section></div>; }

export function PaymentPage() { return <div className="dashboard-page payment-page"><div className="page-intro"><span className="eyebrow">DEMO PAYMENT STATUS</span><h2>Payment details, clearly visible.</h2><p>This is mock procurement payment information. No banking functionality is implemented.</p></div><section className="payment-card"><div className="payment-main"><span><CircleDollarSign size={26} /></span><div><small>PROCUREMENT AMOUNT</small><strong>₹42,500</strong><p>25 quintals wheat • 10 Sep 2026</p></div><StatusBadge status="Payment Initiated" /></div><div className="payment-details"><div><small>Procurement date</small><b>10 September 2026</b></div><div><small>Quantity accepted</small><b>25 quintals</b></div><div><small>Rate (demo)</small><b>₹1,700 / quintal</b></div><div><small>Expected status</small><b>Pending</b></div></div><div className="payment-note"><Clock3 size={18} /><p>Payment reference and bank delivery status will be shown here after secure backend and authorised payment-system integration.</p></div></section></div>; }

export function NotificationsPage() { const [items, setItems] = useState(notifications); const markAll = () => setItems((current) => current.map((item) => ({ ...item, unread: false }))); return <div className="dashboard-page notifications-page"><div className="page-intro split"><div><span className="eyebrow">NOTIFICATIONS</span><h2>Keep up with your procurement.</h2><p>{items.filter((item) => item.unread).length} unread updates need your attention.</p></div><Button variant="secondary" onClick={markAll}>Mark all as read</Button></div><section className="notification-list">{items.map((item) => <article key={item.id} className={item.unread ? 'unread' : ''}><span className={`notification-icon ${item.type}`}>{item.type === 'booking' ? <CalendarCheck2 /> : item.type === 'queue' ? <UsersRound /> : item.type === 'payment' ? <CircleDollarSign /> : <FileCheck2 />}</span><div><b>{item.title}</b><p>{item.time}</p></div>{item.unread && <i aria-label="Unread"></i>}</article>)}</section></div>; }

export function FarmerProfilePage() { return <div className="dashboard-page"><div className="page-intro"><span className="eyebrow">FARMER PROFILE</span><h2>Your account details</h2><p>Profile edit is presented as a non-persistent demo.</p></div><section className="profile-card"><span className="profile-avatar">RK</span><div><h3>Ramesh Kumar</h3><p>Farmer ID: KNF-8421 • Preferred language: English</p></div><div className="profile-grid"><span><small>Mobile</small><b>+91 98••• 28421</b></span><span><small>Location</small><b>Meerut, Uttar Pradesh</b></span><span><small>Village</small><b>Pallavpuram</b></span><span><small>Primary commodity</small><b>Wheat</b></span></div></section></div>; }
