import { Bell, CalendarCheck2, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileCheck2, MapPin, Radio, ReceiptText, Sprout, UsersRound, Wheat } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { Button, LoadingSpinner, SectionTitle, SlotCard, StatusBadge, Timeline } from '../components/UI';
import { api } from '../services/api';
import { getAccessToken } from '../services/api';
import { connectQueueSocket } from '../services/socket';
import { useApp } from '../context/AppContext';

const bookingStatuses = ['booked', 'checked_in', 'quality_check', 'weighed', 'accepted', 'partially_accepted', 'rejected', 'completed', 'cancelled', 'no_show'];
const formatDate = (value) => value ? new Date(value).toLocaleDateString('en-IN') : 'Not available';
const errorText = (error) => error.response?.data?.message || 'Unable to load information.';

function useLatestBooking() {
  const [booking, setBooking] = useState(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { api.getMyBookings().then((items) => setBooking(items[0] || null)).catch(() => setBooking(null)).finally(() => setLoading(false)); }, []);
  return { booking, loading };
}

export function FarmerDashboard() {
  const { user } = useApp();
  const { booking, loading } = useLatestBooking();
  const farmerActions = [[CalendarCheck2, 'Book new slot', 'Choose an available time', '/farmer/book-slot'], [ReceiptText, 'My booking', booking ? booking.bookingCode : 'No active booking', '/farmer/booking'], [UsersRound, 'Live queue', 'View your check-in position', '/farmer/queue'], [FileCheck2, 'Procurement status', 'Track verification and weighing', '/farmer/procurement'], [CircleDollarSign, 'Payment status', 'View settlement details', '/farmer/payment'], [Bell, 'Notifications', 'Review important updates', '/farmer/notifications']];
  if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>;
  return <div className="dashboard-page farmer-dashboard"><div className="welcome-row"><div><span className="eyebrow">WELCOME, {user?.name?.toUpperCase() || 'FARMER'}</span><h2>Your procurement day, made simpler.</h2><p>{booking ? 'Here is the latest on your confirmed booking.' : 'You do not have an active booking yet.'}</p></div><Button to="/farmer/book-slot">Book new slot</Button></div>{booking ? <section className="today-status"><div className="today-status-top"><div><StatusBadge status={booking.status} /><h2>Current procurement status</h2><p>{booking.centreId?.name || 'Selected procurement centre'}</p></div><span className="token-chip">BOOKING <b>{booking.bookingCode}</b></span></div><div className="today-details"><div><MapPin /><span><small>Centre</small><b>{booking.centreId?.name || booking.centreId}</b></span></div><div><Clock3 /><span><small>Date</small><b>{formatDate(booking.bookingDate)}</b></span></div><div><Wheat /><span><small>Quantity</small><b>{booking.bookedQuantity} {booking.quantityUnit}</b></span></div><Button to="/farmer/queue" variant="secondary">View live queue</Button></div></section> : <div className="empty-state"><Sprout size={30} /><h3>No active booking</h3><p>Choose a centre, commodity and available slot to begin.</p></div>}<section><SectionTitle eyebrow="QUICK ACTIONS" title="Everything important, in one place" /><div className="farmer-action-grid">{farmerActions.map(([Icon, title, text, to]) => <Link to={to} className="farmer-action" key={title}><span><Icon size={22} /></span><div><b>{title}</b><p>{text}</p></div><ChevronRight size={19} /></Link>)}</div></section></div>;
}

export function BookSlotPage() {
  const navigate = useNavigate(); const { notify, setBooking } = useApp();
  const [commodities, setCommodities] = useState([]); const [centres, setCentres] = useState([]); const [slots, setSlots] = useState([]);
  const [commodity, setCommodity] = useState(null); const [centre, setCentre] = useState(null); const [slot, setSlot] = useState(null); const [quantity, setQuantity] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { Promise.all([api.getCommodities(), api.getCentres(), api.getAvailableSlots()]).then(([commodityData, centreData, slotData]) => { const nextCommodities = commodityData || []; const nextCentres = centreData.items || centreData || []; const nextSlots = slotData || []; setCommodities(nextCommodities); setCentres(nextCentres); setCommodity(nextCommodities[0] || null); setCentre(nextCentres[0] || null); setSlots(nextSlots); setSlot(nextSlots[0] || null); }).catch((error) => notify(errorText(error), 'error')).finally(() => setLoading(false)); }, []);
  const availableSlots = slots.filter((item) => (!centre || item.centreId?._id === centre._id || item.centreId === centre._id) && (!commodity || item.commodityIds?.some((itemCommodity) => (itemCommodity._id || itemCommodity) === commodity._id)) && item.active && item.remainingCapacity > 0 && (item.remainingQuantity == null || item.remainingQuantity >= Number(quantity || 0)));
  const book = async () => { if (!commodity || !centre || !slot || !quantity) return notify('Select a commodity, centre, slot and quantity.', 'error'); setSaving(true); try { const response = await api.createBooking({ commodityId: commodity._id, centreId: centre._id, slotId: slot._id, bookedQuantity: Number(quantity), quantityUnit: commodity.quantityUnit || 'kg' }); setBooking({ ...response, centreId: centre, commodityId: commodity, slotId: slot }); notify('Your booking has been created.'); navigate('/farmer/booking'); } catch (error) { notify(errorText(error), 'error'); } finally { setSaving(false); } };
  if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>;
  return <div className="dashboard-page booking-page"><div className="page-intro"><span className="eyebrow">SLOT BOOKING</span><h2>Plan your visit around an available slot.</h2><p>Select data configured by an administrator. Availability is validated by the backend.</p></div><section className="booking-section"><div className="booking-section-title"><span>01</span><div><h3>Select commodity</h3><p>Choose what you are bringing to the centre.</p></div></div><div className="commodity-options">{commodities.map((item) => <button key={item._id} className={commodity?._id === item._id ? 'selected' : ''} onClick={() => setCommodity(item)}><Wheat size={24} /><b>{item.name}</b><small>{item.quantityUnit || 'kg'}</small><i>{commodity?._id === item._id && <Check size={15} />}</i></button>)}</div></section><section className="booking-section"><div className="booking-section-title"><span>02</span><div><h3>Select procurement centre</h3><p>Choose a centre that supports your commodity.</p></div></div><div className="booking-centres">{centres.map((item) => <button key={item._id} className={centre?._id === item._id ? 'selected' : ''} onClick={() => setCentre(item)}><MapPin /><span><b>{item.name}</b><small>{item.address}, {item.district}</small></span><StatusBadge status={item.status} /><i>{centre?._id === item._id && <Check size={15} />}</i></button>)}</div></section><section className="booking-section"><div className="booking-section-title"><span>03</span><div><h3>Choose your slot</h3><p>Slots are configured by an administrator.</p></div></div><div className="slot-grid">{availableSlots.map((item) => <SlotCard key={item._id} slot={{ ...item, id: item._id, time: `${item.startTime} – ${item.endTime}`, queue: item.maxFarmers, wait: 'Calculated at check-in', capacity: `${item.maxFarmers} farmers` }} selected={slot?._id === item._id} onSelect={setSlot} />)}</div></section><section className="booking-section"><label>Expected quantity ({commodity?.quantityUnit || 'kg'})<input type="number" min="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} required /></label><Button onClick={book} disabled={saving}>{saving ? 'Booking…' : 'Confirm booking'}</Button></section></div>;
}

export function BookingPage() { const { booking } = useApp(); const [items, setItems] = useState(booking ? [booking] : []); useEffect(() => { if (!booking) api.getMyBookings().then(setItems).catch(() => {}); }, [booking]); const info = items[0]; if (!info) return <div className="dashboard-page"><div className="empty-state"><h3>No booking found</h3><Button to="/farmer/book-slot">Book a slot</Button></div></div>; return <div className="dashboard-page confirmation-page"><div className="confirmation-card"><span className="confirmation-icon"><Check size={40} /></span><span className="eyebrow">BOOKING DETAILS</span><h2>{info.bookingCode}</h2><p>Your booking is stored in Krishi Nova.</p><div className="booking-summary"><div><small>Status</small><b>{info.status}</b></div><div><small>Centre</small><b>{info.centreId?.name || info.centreId}</b></div><div><small>Date</small><b>{formatDate(info.bookingDate)}</b></div><div><small>Quantity</small><b>{info.bookedQuantity} {info.quantityUnit}</b></div></div><div className="confirmation-actions"><Button to="/farmer/queue">View live queue</Button><Button to="/farmer/dashboard" variant="secondary">Back to dashboard</Button></div></div></div>; }

export function QueuePage() { const { booking } = useLatestBooking(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!booking) { setLoading(false); return; } let socket; api.getBookingQueue(booking._id).then((result) => { setItems(result); const entry = result[0]; if (entry && getAccessToken()) { const centreId = entry.centreId?._id || entry.centreId; const slotId = entry.slotId?._id || entry.slotId; socket = connectQueueSocket(getAccessToken(), { updated: (next) => setItems((current) => current.map((item) => item._id === next._id ? next : item)) }); socket.emit('queue:join', { bookingId: booking._id, centreId, slotId, date: booking.bookingDate }); } }).catch(() => setItems([])).finally(() => setLoading(false)); return () => socket?.disconnect(); }, [booking]); if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>; return <div className="dashboard-page queue-page"><div className="live-label"><Radio size={16} /> Live queue <span>Connected to operational updates</span></div><div className="queue-overview"><div className="queue-stat"><small>Queue entries</small><strong>{items.length}</strong><span>Your booking queue</span></div><div className="queue-stat highlight"><small>Estimated wait</small><strong>{items[0]?.estimatedWaitMinutes || 0} <em>min</em></strong><span>Approximate estimate</span></div></div><section className="queue-timeline-section"><div><span className="eyebrow">CENTRE QUEUE</span><h2>Follow your operational status</h2><p>Queue status is maintained by assigned centre staff.</p></div><div className="token-list">{items.map((item) => <div className={item.status} key={item._id}><span><Clock3 size={15} /></span><b>{item.queueNumber}</b><small>{item.status}</small></div>)}</div></section></div>; }

export function ProcurementPage() { const { booking } = useLatestBooking(); const [record, setRecord] = useState(null); useEffect(() => { if (booking) api.getProcurementStatus(booking._id).then(setRecord).catch(() => {}); }, [booking]); const status = record?.status || booking?.status || 'pending'; const items = bookingStatuses.map((item) => ({ title: item.replaceAll('_', ' '), description: item === status ? 'Current procurement status.' : 'Status recorded by the procurement workflow.', status: bookingStatuses.indexOf(item) <= bookingStatuses.indexOf(status) ? 'done' : 'future' })); return <div className="dashboard-page status-page"><div className="page-intro"><span className="eyebrow">PROCUREMENT STATUS</span><h2>Stay informed through every stage.</h2><p>{booking ? `Booking ${booking.bookingCode}` : 'No active booking.'}</p></div><section className="status-timeline-card"><div className="timeline-heading"><div><h3>Procurement progress</h3><p>Latest status from the backend</p></div><StatusBadge status={status} /></div><Timeline items={items} current={status.replaceAll('_', ' ')} /></section></div>; }

export function PaymentPage() { const { booking } = useLatestBooking(); const [payment, setPayment] = useState(null); useEffect(() => { if (booking) api.getPaymentStatus(booking._id).then(setPayment).catch(() => {}); }, [booking]); return <div className="dashboard-page payment-page"><div className="page-intro"><span className="eyebrow">PAYMENT STATUS</span><h2>Settlement details, clearly visible.</h2><p>Payment records are maintained by authorized staff and administrators.</p></div><section className="payment-card">{payment ? <><div className="payment-main"><span><CircleDollarSign size={26} /></span><div><small>PAYABLE AMOUNT</small><strong>{payment.payableAmount ?? 'Not set'}</strong><p>{payment.paymentReference || 'No payment reference yet'}</p></div><StatusBadge status={payment.paymentStatus} /></div><div className="payment-details"><div><small>Status</small><b>{payment.paymentStatus}</b></div><div><small>Paid at</small><b>{formatDate(payment.paidAt)}</b></div></div></> : <div className="empty-state"><Clock3 size={30} /><h3>No settlement record</h3><p>A settlement record will appear after procurement processing.</p></div>}</section></div>; }

export function NotificationsPage() { const [items, setItems] = useState([]); const { notify } = useApp(); useEffect(() => { api.getNotifications().then(setItems).catch((error) => notify(errorText(error), 'error')); }, []); const markAll = async () => { await api.markAllNotificationsRead(); setItems((current) => current.map((item) => ({ ...item, readAt: new Date().toISOString() }))); }; return <div className="dashboard-page notifications-page"><div className="page-intro split"><div><span className="eyebrow">NOTIFICATIONS</span><h2>Keep up with your procurement.</h2><p>{items.filter((item) => !item.readAt).length} unread updates.</p></div><Button variant="secondary" onClick={markAll}>Mark all as read</Button></div><section className="notification-list">{items.map((item) => <article key={item._id} className={!item.readAt ? 'unread' : ''} onClick={() => !item.readAt && api.markNotificationRead(item._id).then(() => setItems((current) => current.map((entry) => entry._id === item._id ? { ...entry, readAt: new Date().toISOString() } : entry)))}><span className={`notification-icon ${item.type}`}><Bell /></span><div><b>{item.title}</b><p>{item.message}</p></div>{!item.readAt && <i aria-label="Unread"></i>}</article>)}</section></div>; }

export function FarmerProfilePage() { const { user } = useApp(); return <div className="dashboard-page"><div className="page-intro"><span className="eyebrow">FARMER PROFILE</span><h2>Your account details</h2><p>Profile data is loaded from your authenticated account.</p></div><section className="profile-card"><span className="profile-avatar">{user?.name?.slice(0, 2).toUpperCase()}</span><div><h3>{user?.name}</h3><p>{user?.role} • Preferred language: {user?.preferredLanguage}</p></div><div className="profile-grid"><span><small>Mobile</small><b>{user?.mobile || 'Not provided'}</b></span><span><small>Email</small><b>{user?.email || 'Not provided'}</b></span><span><small>Account status</small><b>{user?.status}</b></span><span><small>Role</small><b>{user?.role}</b></span></div></section></div>; }
