import { ArrowRight, BarChart3, CalendarCheck2, Check, CheckCircle2, Clock3, Headphones, HeartHandshake, MapPin, Radio, Search, ShieldCheck, Sprout, UsersRound, Wheat } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import heroImage from '../assets/krishi-nova-hero.png';
import { centres } from '../data/centres';
import { Button, CentreCard, SectionTitle, StatCard, StatusBadge } from '../components/UI';

const benefitCards = [
  [Clock3, 'Less Waiting', 'Reduce unnecessary time at procurement centres'],
  [Radio, 'Real-Time Information', 'Know your queue and procurement status'],
  [ShieldCheck, 'Transparent Process', 'Track every stage of procurement'],
  [HeartHandshake, 'Better Farmer Experience', 'Simple and accessible digital service'],
];
const roleCards = [
  { role: 'Farmer', icon: Wheat, colour: 'green', desc: 'Book your procurement slot, check queue status and track your procurement.', items: ['Find procurement centre', 'Book smart slot', 'Track live queue', 'Track procurement and payment'], path: '/login?role=farmer' },
  { role: 'Staff', icon: UsersRound, colour: 'gold', desc: "Manage today's queue, farmer check-ins and procurement operations.", items: ["View today's queue", 'Check-in farmers', 'Manage tokens', 'Mark farmers as served'], path: '/login?role=staff' },
  { role: 'Admin', icon: ShieldCheck, colour: 'blue', desc: 'Manage procurement centres, schedules, staff and analytics.', items: ['Manage centres', 'Manage schedules', 'Monitor analytics', 'Manage staff/system settings'], path: '/login?role=admin' },
];
const steps = [
  ['01', 'Register', 'Create your farmer account'], ['02', 'Select commodity', 'Tell us what you want to procure'], ['03', 'Book smart slot', 'Get an intelligent time recommendation'], ['04', 'Track queue', 'See live position and expected waiting'], ['05', 'Procure', 'Complete verification, quality and weighing'], ['06', 'Get paid', 'Track payment status digitally'],
];

export function HomePage() {
  return <>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="hero-badge"><Sprout size={15} /> For Farmers • For a Stronger Tomorrow</span><h1>Empowering Farmers.<br /><span>Smarter Procurement.</span><br />A Brighter Bharat.</h1><p>Krishi Nova is a transparent and intelligent procurement platform that connects farmers with procurement centres, reduces waiting time, and provides real-time information throughout the procurement journey.</p><div className="hero-actions"><Button to="/login?role=farmer">Get Started</Button><Button to="/how-it-works" variant="secondary">How It Works</Button></div><div className="hero-trust"><span><ShieldCheck /> Transparent process</span><span><Wheat /> Farmer first</span><span><Headphones /> Accessible support</span></div></div><div className="hero-art"><img src={heroImage} alt="Farmer standing in a wheat field near a grain procurement centre" /><div className="hero-info-card"><span><Radio size={17} /></span><div><small>Live centre update</small><b>Normal queue • 23 farmers</b></div></div></div></div></section>
    <section className="benefits wrap"><div className="benefit-grid">{benefitCards.map(([Icon, title, text]) => <article className="benefit" key={title}><span><Icon size={21} /></span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="roles wrap"><SectionTitle eyebrow="ONE PLATFORM, THREE EXPERIENCES" title="A connected procurement ecosystem" text="Designed around the people who make procurement work—farmers, centre teams and administrators." align="center" /><div className="role-grid">{roleCards.map(({ role, icon: Icon, colour, desc, items, path }) => <article className={`role-card ${colour}`} key={role}><div className="role-icon"><Icon size={35} /></div><h3>I am a <span>{role}</span></h3><p>{desc}</p><ul>{items.map((item) => <li key={item}><CheckCircle2 size={16} />{item}</li>)}</ul><Button to={path} variant={colour === 'green' ? 'primary' : colour === 'gold' ? 'gold' : 'blue'}>Continue as {role}</Button></article>)}</div></section>
    <section className="impact"><div className="wrap"><SectionTitle eyebrow="ILLUSTRATIVE PROTOTYPE METRICS" title="Building a more transparent agriculture ecosystem" align="center" /><div className="impact-grid"><StatCard icon={UsersRound} value="10K+" label="Farmers Connected" note="Prototype scale" /><StatCard icon={MapPin} value="500+" label="Procurement Centres" note="Demo network" /><StatCard icon={Wheat} value="2M+" label="Quintals Procured" note="Illustrative data" /><StatCard icon={BarChart3} value="98%" label="Service Satisfaction" note="Prototype target" /></div></div></section>
    <section className="journey wrap"><SectionTitle eyebrow="HOW KRISHI NOVA WORKS" title="From field to fair payment—without the uncertainty" text="A guided journey that keeps every farmer informed at every stage." align="center" /><div className="process-track">{steps.map(([number, title, text], index) => <div className="process-step" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p>{index < steps.length - 1 && <i><ArrowRight size={19} /></i>}</div>)}</div><div className="section-action"><Button to="/how-it-works" variant="secondary">Explore the full journey</Button></div></section>
    <section className="about-band"><div className="wrap about-grid"><div><span className="eyebrow">PROPOSED DIGITAL PLATFORM</span><h2>Technology for a more transparent procurement journey</h2><p>Krishi Nova connects farmers, procurement-centre staff and administrators through one digital platform—making schedules, queues, operations and payments easier to understand and manage.</p><ul><li><CheckCircle2 /> Clear, real-time process visibility</li><li><CheckCircle2 /> Better centre planning and capacity management</li><li><CheckCircle2 /> A simpler experience for every farmer</li></ul><Button to="/about" variant="secondary">About Krishi Nova</Button></div><div className="about-visual"><div className="leaf-pattern"></div><span className="visual-stat"><Wheat size={25} /><b>Smart slots</b><small>Lower predicted wait</small></span><span className="visual-stat second"><Clock3 size={25} /><b>Live queue</b><small>Always informed</small></span><div className="visual-centre"><MapPin size={34} /><b>Connected centres</b><small>Simple access across districts</small></div></div></div></section>
  </>;
}

export function AboutPage() { return <PublicInfoPage eyebrow="ABOUT KRISHI NOVA" title="Technology for a more transparent procurement journey" lead="An SIH prototype exploring a clearer, more efficient connection between farmers and procurement centres."><div className="info-grid"><article><ShieldCheck /><h3>Transparency first</h3><p>Every key stage—from booking to payment—can be understood and tracked without guesswork.</p></article><article><Clock3 /><h3>Time respected</h3><p>Smart recommendations and live queue information help farmers plan their visit more confidently.</p></article><article><UsersRound /><h3>Centres enabled</h3><p>Operations teams see queue conditions and capacity signals to make everyday decisions easier.</p></article></div><div className="callout"><h3>Built for a public-service experience</h3><p>Krishi Nova does not represent an official government system. It is a proposed digital platform created for the Smart India Hackathon prototype experience.</p></div></PublicInfoPage>; }

export function ContactPage() { return <PublicInfoPage eyebrow="CONTACT & SUPPORT" title="We are here to help your procurement journey" lead="For the prototype, the following channels are illustrative. In a production rollout, local language support and district help desks can be connected here."><div className="contact-grid"><article><Headphones /><b>Farmer support helpline</b><a href="tel:18001234567">1800-123-4567</a><small>Mon–Sat, 9:00 AM–6:00 PM</small></article><article><MapPin /><b>Find a nearby centre</b><Link to="/centres">Explore procurement centres</Link><small>Check live availability before visiting</small></article><article><HeartHandshake /><b>Demo support</b><a href="mailto:help@krishinova.demo">help@krishinova.demo</a><small>Prototype support channel</small></article></div></PublicInfoPage>; }

export function HowItWorksPage() {
  const journey = ['Registration', 'Select commodity', 'Centre selection', 'Demand & queue analysis', 'Smart slot recommendation', 'Booking', 'Arrival', 'Quality check', 'Weighing', 'Procurement', 'Payment'];
  return <><section className="page-hero"><div className="wrap"><span className="eyebrow">FARMER JOURNEY</span><h1>A clear journey from registration to payment</h1><p>Krishi Nova keeps the important information visible, so a farmer can plan with confidence before leaving for the centre.</p></div></section><section className="wrap how-page"><div className="journey-list">{journey.map((name, index) => <div className={name === 'Smart slot recommendation' ? 'journey-node featured' : 'journey-node'} key={name}><span>{String(index + 1).padStart(2, '0')}</span><div><h3>{name}</h3><p>{journeyCopy[name]}</p></div>{index < journey.length - 1 && <i></i>}</div>)}</div><aside className="recommendation-panel"><span className="demo-pill">ML Recommendation (Demo)</span><h2>Smart Slot Recommendation</h2><p>The platform combines centre capacity, current queue conditions and historical demand patterns to suggest an easier time to visit.</p><div className="recommended-time"><small>Recommended slot</small><b>12:00 – 1:00 PM</b></div><div className="recommend-stats"><span><small>Expected waiting</small><b>25–35 min</b></span><span><small>Queue load</small><b className="green-text">Low</b></span></div><p className="fine-print">Recommendation logic is demo data until an ML service is connected.</p><Button to="/farmer/book-slot">Try smart slot booking</Button></aside></section></>;
}
const journeyCopy = { Registration: 'Create a simple farmer account using mobile OTP.', 'Select commodity': 'Choose the crop you want to bring for procurement.', 'Centre selection': 'Compare nearby centres and their current status.', 'Demand & queue analysis': 'Demo logic reviews workload and capacity signals.', 'Smart slot recommendation': 'Receive a suggested time with a predicted wait.', Booking: 'Confirm your preferred slot and receive a token.', Arrival: 'Check in at the selected procurement centre.', 'Quality check': 'Produce is assessed using the centre process.', Weighing: 'Accepted quantity is recorded and displayed.', Procurement: 'Procurement is marked completed.', Payment: 'Track the demo payment status digitally.' };

export function CentresPage() {
  const [term, setTerm] = useState(''); const [district, setDistrict] = useState('All districts'); const [status, setStatus] = useState('All status'); const [selected, setSelected] = useState(null);
  const filtered = useMemo(() => centres.filter((centre) => (!term || `${centre.name} ${centre.location}`.toLowerCase().includes(term.toLowerCase())) && (district === 'All districts' || centre.district === district) && (status === 'All status' || centre.status === status)), [term, district, status]);
  return <><section className="page-hero centres-hero"><div className="wrap"><span className="eyebrow">PROCUREMENT CENTRES</span><h1>Find a centre that works for your day</h1><p>Compare available slots, current queues and capacity before you travel.</p></div></section><section className="wrap centres-page"><div className="filter-bar"><label><Search size={18} /><input value={term} onChange={(event) => setTerm(event.target.value)} placeholder="Search centre or location" /></label><select value={district} onChange={(event) => setDistrict(event.target.value)} aria-label="Filter by district"><option>All districts</option><option>Meerut</option><option>Hapur</option><option>Ghaziabad</option></select><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter by status"><option>All status</option><option>Normal</option><option>Moderate</option><option>High</option></select></div><div className="centres-layout"><div className="centre-list"><p className="result-count">{filtered.length} centres found</p>{filtered.map((centre) => <CentreCard key={centre.id} centre={centre} onSelect={setSelected} />)}</div><aside className="map-placeholder"><div className="map-dots"><i></i><i></i><i></i><i></i></div><span><MapPin size={30} /></span><b>Centre map</b><p>Map integration placeholder</p>{selected && <div className="map-selected"><b>{selected.name}</b><p>{selected.location}</p><StatusBadge status={selected.status} /><Button to={`/login?role=farmer&centre=${selected.id}`} variant="primary">Book at this centre</Button></div>}</aside></div></section></>;
}

function PublicInfoPage({ eyebrow, title, lead, children }) { return <><section className="page-hero"><div className="wrap"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{lead}</p></div></section><section className="wrap info-page">{children}</section></>; }
