import { AlertTriangle, CheckCircle2, Clock3, Gauge, PackageCheck, UsersRound } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button, LoadingSpinner, StatCard, StatusBadge } from '../components/UI';
import { api } from '../services/api';
import { useApp } from '../context/AppContext';

function QueueTable({ items, onUpdate, compact = false }) { return <div className="table-wrap"><table className="queue-table"><thead><tr><th>Queue</th><th>Farmer</th><th>Quantity</th><th>Status</th><th>Checked in</th>{!compact && <th>Action</th>}</tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><b>{item.queueNumber}</b></td><td>{item.farmerId?.name || 'Farmer'}</td><td>{item.bookingId?.bookedQuantity || '—'} {item.bookingId?.quantityUnit || ''}</td><td><StatusBadge status={item.status} /></td><td>{item.checkedInAt ? new Date(item.checkedInAt).toLocaleTimeString() : '—'}</td>{!compact && <td><div className="row-actions">{item.status === 'checked_in' && <button onClick={() => onUpdate(item, 'processing')}>Start processing</button>}{item.status === 'processing' && <button className="served" onClick={() => onUpdate(item, 'served')}>Mark served</button>}{item.status === 'waiting' && <button onClick={() => onUpdate(item, 'checked_in')}>Check in</button>}</div></td>}</tr>)}</tbody></table></div>; }

function useStaffQueue() { const { user, notify } = useApp(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const centreId = user?.assignedCentreIds?.[0]; useEffect(() => { if (!centreId) { setLoading(false); return; } api.getQueue({ centreId }).then(setItems).catch((error) => notify(error.response?.data?.message || 'Unable to load queue.', 'error')).finally(() => setLoading(false)); }, [centreId]); const update = async (item, status) => { try { const result = await api.updateQueueStatus(item._id, status); setItems((current) => current.map((entry) => entry._id === item._id ? result : entry)); } catch (error) { notify(error.response?.data?.message || 'Unable to update queue.', 'error'); } }; return { items, loading, update }; }

export function StaffDashboard() { const { items, loading, update } = useStaffQueue(); if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>; const waiting = items.filter((item) => item.status === 'waiting' || item.status === 'checked_in').length; const processing = items.filter((item) => item.status === 'processing').length; const completed = items.filter((item) => item.status === 'served').length; return <div className="dashboard-page staff-page"><div className="welcome-row"><div><span className="eyebrow">CENTRE OPERATIONS</span><h2>Today’s centre operations</h2><p>Monitor assigned-centre queue activity.</p></div><span className="date-chip">Live data</span></div><section className="staff-stats"><StatCard icon={UsersRound} value={items.length} label="Queue entries" note="Current scope" accent="green" /><StatCard icon={Clock3} value={waiting} label="Waiting" note="Active queue" accent="gold" /><StatCard icon={PackageCheck} value={processing} label="Processing" note="In operation" accent="blue" /><StatCard icon={CheckCircle2} value={completed} label="Completed" note="Served entries" accent="green" /><StatCard icon={Gauge} value="—" label="Average waiting" note="Calculated from queue data" accent="gold" /><StatCard icon={Gauge} value="—" label="Centre capacity" note="Configured by admin" accent="blue" /></section><section className="operations-card"><div className="section-row"><div><span className="eyebrow">LIVE QUEUE</span><h2>Manage active farmers</h2></div><Button to="/staff/queue" variant="secondary">Full queue</Button></div><QueueTable items={items} onUpdate={update} compact /></section></div>; }

export function StaffQueuePage() { const { items, loading, update } = useStaffQueue(); if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>; return <div className="dashboard-page staff-page"><div className="page-intro"><span className="eyebrow">LIVE QUEUE MANAGEMENT</span><h2>Check in and serve farmers in order.</h2><p>Actions update the assigned centre queue.</p></div><section className="operations-card full-table"><QueueTable items={items} onUpdate={update} /></section></div>; }

export function StaffBookingsPage() { const { items, loading } = useStaffQueue(); if (loading) return <div className="dashboard-page"><LoadingSpinner /></div>; return <div className="dashboard-page staff-page"><div className="page-intro"><span className="eyebrow">CURRENT BOOKINGS</span><h2>Expected arrivals and operational allocation</h2><p>{items.length} queue entries are currently available for this centre.</p></div><section className="operations-card"><div className="section-row"><h2>Assigned-centre entries</h2><StatusBadge status="Live" /></div><QueueTable items={items} onUpdate={() => {}} compact /></section></div>; }
