import { AlertTriangle, CheckCircle2, Clock3, Gauge, PackageCheck, UsersRound } from 'lucide-react';
import { useState } from 'react';
import { Button, StatCard, StatusBadge } from '../components/UI';
import { staffQueue } from '../data/dashboard';
import { useApp } from '../context/AppContext';

function QueueTable({ compact = false }) {
  const [items, setItems] = useState(staffQueue); const { notify } = useApp();
  const update = (token, status) => { setItems((current) => current.map((item) => item.token === token ? { ...item, status } : item)); notify(`${token} marked as ${status.toLowerCase()}.`); };
  return <div className="table-wrap"><table className="queue-table"><thead><tr><th>Token</th><th>Farmer</th><th>Quantity</th><th>Status</th><th>ETA</th>{!compact && <th>Action</th>}</tr></thead><tbody>{items.map((item) => <tr key={item.token}><td><b>{item.token}</b></td><td>{item.farmer}</td><td>{item.quantity}</td><td><StatusBadge status={item.status} /></td><td>{item.eta}</td>{!compact && <td><div className="row-actions">{item.status === 'Waiting' && <button onClick={() => update(item.token, 'Check-in')}>Check In</button>}{item.status === 'Check-in' && <button onClick={() => update(item.token, 'Processing')}>Start Processing</button>}{item.status === 'Processing' && <button className="served" onClick={() => update(item.token, 'Served')}>Mark Served</button>}</div></td>}</tr>)}</tbody></table></div>;
}

export function StaffDashboard() { return <div className="dashboard-page staff-page"><div className="welcome-row"><div><span className="eyebrow">GOVERNMENT PROCUREMENT CENTRE • MEERUT</span><h2>Today’s centre operations</h2><p>Monitor arrival flow and keep farmers moving smoothly.</p></div><span className="date-chip">10 Sep 2026</span></div><section className="staff-stats"><StatCard icon={UsersRound} value="124" label="Today's farmers" note="38 scheduled to arrive" accent="green" /><StatCard icon={Clock3} value="21" label="Waiting" note="Current active queue" accent="gold" /><StatCard icon={PackageCheck} value="6" label="Processing" note="At quality or weighing" accent="blue" /><StatCard icon={CheckCircle2} value="60" label="Completed" note="Updated today" accent="green" /><StatCard icon={Gauge} value="31 min" label="Average waiting" note="Demo average" accent="gold" /><StatCard icon={Gauge} value="78%" label="Centre capacity" note="Today’s utilisation" accent="blue" /></section><section className="risk-card"><span><AlertTriangle size={24} /></span><div><b>Moderate congestion expected around 11:00 AM.</b><p>12 scheduled arrivals overlap with current check-ins. Consider opening a second verification desk.</p></div><Button variant="secondary" to="/staff/queue">View queue</Button></section><section className="operations-card"><div className="section-row"><div><span className="eyebrow">LIVE QUEUE</span><h2>Manage active farmers</h2></div><Button to="/staff/queue" variant="secondary">Full queue</Button></div><QueueTable compact /></section></div>; }

export function StaffQueuePage() { return <div className="dashboard-page staff-page"><div className="page-intro"><span className="eyebrow">LIVE QUEUE MANAGEMENT</span><h2>Check in and serve farmers in order.</h2><p>Buttons use demo state only. Production actions can call authenticated centre APIs from the service layer.</p></div><section className="operations-card full-table"><QueueTable /></section></div>; }

export function StaffBookingsPage() { return <div className="dashboard-page staff-page"><div className="page-intro"><span className="eyebrow">TODAY'S BOOKINGS</span><h2>Expected arrivals and smart-slot allocation</h2><p>126 slot bookings are scheduled today. 38 farmers are due within the next two hours.</p></div><section className="booking-summary-staff"><div><small>10:00–11:00 AM</small><b>29 farmers</b><span>High demand</span></div><div><small>11:00 AM–12:00 PM</small><b>41 farmers</b><span>Moderate congestion</span></div><div className="best"><small>12:00–1:00 PM</small><b>18 farmers</b><span>Recommended window</span></div><div><small>1:00–2:00 PM</small><b>25 farmers</b><span>Available capacity</span></div></section><section className="operations-card"><div className="section-row"><h2>Upcoming bookings</h2><StatusBadge status="Normal" /></div><QueueTable compact /></section></div>; }
