import { z } from 'zod';
const id = z.string().regex(/^[a-f\d]{24}$/i);
export const centreSchema = z.object({ centreCode: z.string().min(2), name: z.string().min(2), address: z.string().min(2), district: z.string().min(2), state: z.string().min(2), pincode: z.string().optional(), status: z.enum(['active', 'inactive']).optional(), supportedCommodityIds: z.array(id).optional(), operatingHours: z.array(z.object({ day: z.number().int().min(0).max(6), open: z.string().optional(), close: z.string().optional(), closed: z.boolean().optional() })).optional() });
export const commoditySchema = z.object({ name: z.string().min(2), code: z.string().min(2), description: z.string().optional(), quantityUnit: z.string().default('kg'), active: z.boolean().optional(), qualityParameters: z.array(z.object({ key: z.string(), label: z.string(), type: z.enum(['number', 'text', 'select']), required: z.boolean().optional() })).optional(), rejectionReasons: z.array(z.string()).optional() });
const numeric = (schema) => z.preprocess((value) => value === '' || value === undefined ? undefined : Number(value), schema);
export const slotSchema = z.object({ centreId: id, scheduleId: id.optional(), commodityIds: z.array(id).optional(), supportedCommodities: z.array(z.string().trim().min(1)).optional(), date: z.coerce.date(), startTime: z.string(), endTime: z.string(), maxFarmers: numeric(z.number().int().positive()), maxQuantity: numeric(z.number().positive().optional()), quantityUnit: z.string().default('kg'), bookingCutoffMinutes: numeric(z.number().int().nonnegative().default(60)), active: z.boolean().optional() });
export const bookingSchema = z.object({ centreId: id, slotId: id, commodityId: id.optional(), commodityName: z.string().trim().min(1).optional(), bookedQuantity: z.number().positive(), quantityUnit: z.string().default('kg') }).refine((data) => Boolean(data.commodityId || data.commodityName), { message: 'commodityId or commodityName is required', path: ['commodityId'] });
export const procurementScheduleSchema = z.object({ centreId: id, name: z.string().trim().optional(), supportedCommodities: z.array(z.string().trim().min(1)).min(1), effectiveFrom: z.coerce.date(), effectiveUntil: z.coerce.date(), daysOfWeek: z.array(z.number().int().min(0).max(6)).min(1), openingTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), closingTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), slotDurationMinutes: numeric(z.number().int().min(5).max(480).default(30)), maxFarmersPerSlot: numeric(z.number().int().positive()), maxQuantityPerSlot: numeric(z.number().positive().optional()), quantityUnit: z.string().default('kg'), bookingCutoffMinutes: numeric(z.number().int().nonnegative().default(60)), active: z.boolean().optional() });
export const schedulePreviewSchema = z.object({ centreId: id, effectiveFrom: z.coerce.date(), effectiveUntil: z.coerce.date(), daysOfWeek: z.array(z.number().int().min(0).max(6)).min(1), openingTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), closingTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/), slotDurationMinutes: numeric(z.number().int().min(5).max(480).default(30)), maxFarmersPerSlot: numeric(z.number().int().positive()) });
export const cancelSchema = z.object({ reason: z.string().max(500).optional() });

export const queueStatusSchema = z.object({ status: z.enum(['waiting', 'checked_in', 'processing', 'served', 'skipped', 'cancelled', 'no_show']) });
export const skipSchema = z.object({ reason: z.string().min(2).max(500) });
